# Generated by Django 3.2.2 on 2021-07-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
