# Generated by Django 3.2.2 on 2021-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
